### ISSUE TITLE
MidHashToSign does not declare a serialVersionUID

### ISSUE THREAD

**Issue by ristosaar** [SK-EID/mid-rest-java-client#20]
The MidHashToSign does not declare a serialVersionUID so session deserialization might break in the future.

Please add a serialVersionUID to https://github.com/SK-EID/mid-rest-java-client/blob/master/src/main/java/ee/sk/mid/MidHashToSign.java

I would create a PR myself but I don't have the access rights

**Comment by aasaru** [comment]
This issue is now reloved (by #29) and will be available in version 1.2
