### ISSUE TITLE
The hard-coded SSL certificate for demo environment has expired

### ISSUE THREAD

**Issue by Infeligo** [SK-EID/mid-rest-java-client#31]
The expired certificate can be found in [`MidClient.java`](https://github.com/SK-EID/mid-rest-java-client/blob/master/src/main/java/ee/sk/mid/MidClient.java#L73). This is nothing critical as there are several ways to specify a newer certificate, but still causes a bit of set back.

**Comment by virtual-machinist** [comment]
What scares me more is the previous line.

```
private static final String SSL_CERT_VALID_FROM_2019_03_21_TO_2021_03_25 = ...
```

Why make a constant of something that is bound to change?

**Comment by aasaru** [comment]
Internal issue id: DDS-2851
