### ISSUE TITLE
Embedded CA truststore classpath name clashes with the one from SmartID Java Client

### ISSUE THREAD

**Issue by Infeligo** [SK-EID/mid-rest-java-client#33]
[`MidAuthenticationResponseValidator`](https://github.com/SK-EID/mid-rest-java-client/blob/ca1add0b2ccb75e51970dfb661a24684152a1d98/src/main/java/ee/sk/mid/MidAuthenticationResponseValidator.java#L160) loads trusted CA certificates from a classpath resource called `trusted_certificates.jks` located in resources directory of the library. However, when SmartID Java Client is also present on the classpath, another truststore with the same name is defined on the classpath and it is undetermined if MID Java Client loads the correct truststore or not.

My suggestion would be to rename `trusted_certificates.jks` to a more specific `mid_trusted_certificates.jks`.

Additionally, there is no method like `clearTrustedCACertificates()` in SmartID Java Client to remove the certificates loaded by default in case I want to rely purely on the ones added via `addTrustedCACertificate(..)`.

**Comment by aasaru** [comment]
Thank you for the report!
This is resolved in https://github.com/SK-EID/mid-rest-java-client/releases/tag/1.3
This task can now be closed.
